/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.scheme.ui.AbstractSchemeUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SchemeUiModule extends AbstractSchemeUiModule {
  public SchemeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
