/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme.ide;

import org.xtext.example.scheme.ide.AbstractSchemeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SchemeIdeModule extends AbstractSchemeIdeModule {
}
