/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSchemeScopeProvider extends DelegatingScopeProvider {
}
