/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.List#getCalle <em>Calle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.List#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList()
 * @model
 * @generated
 */
public interface List extends Expression
{
  /**
   * Returns the value of the '<em><b>Calle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calle</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calle</em>' attribute.
   * @see #setCalle(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList_Calle()
   * @model
   * @generated
   */
  String getCalle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.List#getCalle <em>Calle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Calle</em>' attribute.
   * @see #getCalle()
   * @generated
   */
  void setCalle(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getList_Params()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getParams();

} // List
