/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme;

import org.xtext.example.scheme.SchemeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchemeStandaloneSetup extends SchemeStandaloneSetupGenerated {
  public static void doSetup() {
    new SchemeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
