/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme;

import org.xtext.example.scheme.AbstractSchemeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchemeRuntimeModule extends AbstractSchemeRuntimeModule {
}
