/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme.validation;

import org.xtext.example.scheme.validation.AbstractSchemeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SchemeValidator extends AbstractSchemeValidator {
}
