/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scheme.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.scheme.ui.internal.SchemeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SchemeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SchemeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SchemeActivator.getInstance().getInjector(SchemeActivator.ORG_XTEXT_EXAMPLE_SCHEME_SCHEME);
	}
	
}
